/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : MOTOR1DIR.H
**     Project   : TestErectCar
**     Processor : 56F8013VFAE
**     Component : ExtInt
**     Version   : Component 02.094, Driver 02.04, CPU db: 2.87.097
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011-12-4, 23:11
**     Abstract  :
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : INT_GPIO_B
**         User handling procedure     : MOTOR1DIR_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       4             |  GPIOB5_T1_FAULT3
**             ----------------------------------------------------
**
**         Port name                   : GPIOB
**
**         Bit number (in port)        : 5
**         Bit mask of the port        : 32
**
**         Signal edge/level           : rising
**         Priority                    : 1
**         Pull option                 : off
**         Initial state               : Enabled
**
**         Edge register               : GPIO_B_IPOLR [61718]
**         Priority register           : INTC_IPR1 [61537]
**         Enable register             : GPIO_B_IENR [61717]
**         Request register            : GPIO_B_IESR [61720]
**
**         Port data register          : GPIO_B_DR [61713]
**         Port control register       : GPIO_B_DDR [61714]
**         Port function register      : GPIO_B_PER [61715]
**     Contents  :
**         GetVal - bool MOTOR1DIR_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __MOTOR1DIR_H
#define __MOTOR1DIR_H

/* MODULE MOTOR1DIR. */

/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


#define MOTOR1DIR_PIN_MASK      ((byte)32) /* Pin mask */

void MOTOR1DIR_Interrupt(void);
/*
** ===================================================================
**     Method      :  MOTOR1DIR_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and invokes the beans event.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define MOTOR1DIR_GetVal() ((bool)(getRegBits(GPIO_B_RAWDATA,MOTOR1DIR_PIN_MASK)))
/*
** ===================================================================
**     Method      :  MOTOR1DIR_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/

/* END MOTOR1DIR. */

#endif /* __MOTOR1DIR_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
