/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : MOTOR1DIRVAL.H
**     Project   : TestErectCar
**     Processor : 56F8013VFAE
**     Component : BitIO
**     Version   : Component 02.075, Driver 01.18, CPU db: 2.87.097
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011-12-5, 0:08
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Input direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       30            |  TDI_GPIOD0
**             ----------------------------------------------------
**
**         Port name                   : GPIOD
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : 1
**
**         Initial direction           : Input (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : GPIO_D_DR [61745]
**         Port control register       : GPIO_D_DDR [61746]
**         Port function register      : GPIO_D_PER [61747]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool MOTOR1DIRVAL_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __MOTOR1DIRVAL_H
#define __MOTOR1DIRVAL_H

/* MODULE MOTOR1DIRVAL. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"


#define MOTOR1DIRVAL_PIN_MASK   ((byte)1) /* Pin mask */


/*
** ===================================================================
**     Method      :  MOTOR1DIRVAL_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Input direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define MOTOR1DIRVAL_GetVal() ((bool)(getRegBits(GPIO_D_DR,MOTOR1DIRVAL_PIN_MASK)))


/* END MOTOR1DIRVAL. */

#endif /* __MOTOR1DIRVAL_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
